name: AWS session
on:
  workflow_call:
    secrets:
      aws_access_key_id_repo:
        required: true
      aws_secret_access_key_repo:
        required: true

jobs:
  aws-session:
    name: 'AWS session'
    runs-on: ubuntu-latest
    steps:
      - name: 'AWS session'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id_repo }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key_repo }}
        run: |
          accessData=`aws sts assume-role --role-arn "arn:aws:iam::242906888793:role/AWS_Sandbox" --role-session-name MaksimUlyanov`
          export AWS_ACCESS_KEY_ID=`echo $accessData | jq .Credentials.AccessKeyId -r`
          export AWS_SESSION_TOKEN=`echo $accessData | jq .Credentials.SessionToken -r`
          export AWS_SECRET_ACCESS_KEY=`echo $accessData | jq .Credentials.SecretAccessKey -r`
