name: Deploy
on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID_REPO:
        required: true
      AWS_SECRET_ACCESS_KEY_REPO:
        required: true
env:
  AWS_DEFAULT_REGION: us-east-1
jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Establish AWS session'
        uses: './.github/actions/aws-session'
        with:
          AWS_ACCESS_KEY_ID_REPO: ${{ secrets.AWS_ACCESS_KEY_ID_REPO }}
          AWS_SECRET_ACCESS_KEY_REPO: ${{ secrets.AWS_SECRET_ACCESS_KEY_REPO }}
