name: Docker Push
on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID_REPO:
        required: true
      AWS_SECRET_ACCESS_KEY_REPO:
        required: true
env:
  AWS_DEFAULT_REGION: us-east-1
jobs:
  docker-push:
    name: 'Docker Push'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - name: 'Establish AWS session'
        uses: './.github/actions/aws-session'
        with:
          AWS_ACCESS_KEY_ID_REPO: ${{ secrets.AWS_ACCESS_KEY_ID_REPO }}
          AWS_SECRET_ACCESS_KEY_REPO: ${{ secrets.AWS_SECRET_ACCESS_KEY_REPO }}
      - name: 'Clone cred helper repo'
        run: git clone "https://github.com/awslabs/amazon-ecr-credential-helper.git"
      - name: 'Build Cred Helper'
        working-directory: ./amazon-ecr-credential-helper
        run: make docker
      - name: 'Setup Docker'
        run: jq '.credHelpers += {"242906888793.dkr.ecr.us-east-1.amazonaws.com":"ecr-login"}' ~/.docker/config.json > ~/.docker/config.json
      - run: cat ~/.docker/config.json
