name: Master CI
on:
  push:
    branches:
      - 'master'
jobs:
  ci-pipeline:
    name: 'Build & Test'
    uses: './.github/workflows/build-test.yml'
  cd-pipeline:
    needs: [ ci-pipeline ]
    name: 'Deploy'
    uses: './.github/workflows/deploy.yml'
