name: Master workflow
on:
  push:
    branches:
      - 'master'
jobs:
  ci-pipeline:
    name: 'Build & Test'
    uses: './.github/workflows/build-test.yml'
  cd-pipeline:
    needs: [ ci-pipeline ]
    name: 'Deploy'
    uses: './.github/workflows/deploy.yml'
    secrets:
      AWS_ACCESS_KEY_ID_REPO: ${{ secrets.AWS_ACCESS_KEY_ID_REPO }}
      AWS_SECRET_ACCESS_KEY_REPO: ${{ secrets.AWS_SECRET_ACCESS_KEY_REPO }}
