name: Master workflow
on:
  push:
    branches:
      - 'master'
jobs:
  build-test:
    name: 'Build & Test'
    uses: './.github/workflows/build-test.yml'
  terraform-deploy:
    needs: [ build-test ]
    name: 'Terraform Deploy'
    uses: './.github/workflows/terraform-deploy.yml'
    secrets:
      AWS_ACCESS_KEY_ID_REPO: ${{ secrets.AWS_ACCESS_KEY_ID_REPO }}
      AWS_SECRET_ACCESS_KEY_REPO: ${{ secrets.AWS_SECRET_ACCESS_KEY_REPO }}
  docker-push:
    needs: [ terraform-deploy ]
    name: 'Docker Push'
    uses: './.github/workflows/docker-push.yml'
    secrets:
      AWS_ACCESS_KEY_ID_REPO: ${{ secrets.AWS_ACCESS_KEY_ID_REPO }}
      AWS_SECRET_ACCESS_KEY_REPO: ${{ secrets.AWS_SECRET_ACCESS_KEY_REPO }}
