name: Pull request workflow
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  #build-test:
  #  name: 'Build & Test'
  #  uses: './.github/workflows/build-test.yml'
  #terraform-plan:
  #  needs: [ build-test ]
  #  name: 'Terraform Plan'
  #  uses: './.github/workflows/terraform-plan.yml'
  #  secrets:
  #    AWS_ACCESS_KEY_ID_REPO: ${{ secrets.AWS_ACCESS_KEY_ID_REPO }}
  #    AWS_SECRET_ACCESS_KEY_REPO: ${{ secrets.AWS_SECRET_ACCESS_KEY_REPO }}
  docker-push:
    name: 'Docker Push'
    uses: './.github/workflows/docker-push.yml'
