name: Pull request CI
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
#  ci-pipeline:
#    name: 'Build & Test'
#    uses: './.github/workflows/build-test.yml'
  cd-pipeline:
#    needs: [ ci-pipeline ]
    name: 'Deploy'
    uses: './.github/workflows/deploy.yml'
